name = "HOHQMesh"
uuid = "e4f4c7b8-17cb-445a-93c5-f69190ed6c8c"
authors = ["Michael Schlottke-Lakemper <michael@sloede.com>", "Andrew R. Winters <andrew.ross.winters@liu.se>"]
version = "0.2.2-pre"

[deps]
HOHQMesh_jll = "1d5cbd98-5122-5a8a-bea1-c186d986ee7f"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
HOHQMesh_jll = "1.0"
Requires = "1.1.3"
julia = "1.6"
