name = "HOHQMesh"
uuid = "e4f4c7b8-17cb-445a-93c5-f69190ed6c8c"
authors = ["Michael Schlottke-Lakemper <michael@sloede.com>"]
version = "0.1.0"

[deps]
HOHQMesh_jll = "1d5cbd98-5122-5a8a-bea1-c186d986ee7f"

[compat]
HOHQMesh_jll = "1.0"
julia = "1.6"
