[deps]
Changelog = "5217a498-cd5d-4ec6-b8c2-9b85a09b6e3e"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HOHQMesh = "e4f4c7b8-17cb-445a-93c5-f69190ed6c8c"

[compat]
Changelog = "1.1"
Documenter = "1.3"
